# Generated by Django 4.1.3 on 2022-11-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rating_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='commemt',
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
