# Generated by Django 4.1.3 on 2022-11-25 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0004_remove_rating_commemt_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
