# Generated by Django 4.1.3 on 2022-11-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_place_active_place_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
